### PR TITLE
Add P3563 and P 3723 (NGA and USCG Lists of lights)

### PR DESCRIPTION
**Pull request by pyrog**

### CODE REVIEW

**Review by arthurpsmith — CHANGES_REQUESTED** [review]
A couple of issues here for property 3563:
* For id's that don't start with 11x- there is no volume, and as far as I can tell the proposed URL fails - for example https://msi.nga.mil/queryResults?publications/ngalol/lights-buoys?volume=&featureNumber=9264&includeRemovals=false&output=html for the id 9264 which is used on Q259658. Does this formatter only work on id's with a volume number? What fraction meet that criterion?

* It is far better to have most of the URL not hard-wired in this code, but to use the url_prefix and url_suffix parameters to supply that from the formatter URL - that lets the exact URL be modified in Wikidata if there's a need, rather than updating the code here. Ideally the only think in $link_string should be the "volume=$a[1]&featureNumber=$a[2]" bit. Or even just "$a[1]&featureNumber=$a[2]" with the volume= part in the url_prefix value.

**Review by arthurpsmith — CHANGES_REQUESTED** [review]
For 3723 there doesn't seem to be the same issue with the volume - looks like everything includes the volume prefix and the URL does work for ones I tried.
I'd still prefer that you move most of the text of the URL to the url_prefix value in the formatter, and leave just the volume=$a[1]&featureNumber=$a[2] bit in $link_string here.

**Comment by pyrog** [comment]
>For id's that don't start with 11x- there is no volume, and as far as I can tell the proposed URL fails
No, just click on each "undefined" to get the beacon.

An NGA ID without a volume number is not valid. The format constraint of [P3563](https://www.wikidata.org/wiki/Property:P3563) must be updated.
All data should be cleaned

**Comment by pyrog** [comment]
> It is far better to have most of the URL not hard-wired in this code, but to use the url_prefix and url_suffix parameters to supply that from the formatter URL

Ok, I understand 😄 

**Note:** same issue for [P345](https://github.com/arthurpsmith/wikidata-tools/blob/master/wikidata-externalid-url/index.php#L42), [P6841](https://github.com/arthurpsmith/wikidata-tools/blob/master/wikidata-externalid-url/index.php#L136), [P6996](https://github.com/arthurpsmith/wikidata-tools/blob/master/wikidata-externalid-url/index.php#L141)… 😉

I suggest to use another mechanism to do that. Pass two parameters:
1. a regex that split ID
2. an URL with e.g. `%1`, `%2`…, where `%1`, `%2`… will be replaced by the rows of the matches array passed to preg_match()

We can't use `$1` because it is already used by [formatter URL](https://www.wikidata.org/wiki/Property:P1630) or [third-party formatter URL](https://www.wikidata.org/wiki/Property:P3303).

The goal of the regex is not to validate `$id`, just split it to set `$redirect_url`.
(This the job of [format constraint](https://www.wikidata.org/wiki/Q21502404) to check IDs).
So we could use a "simple" regex…

With this concept, the same code could work for properties [3563](https://www.wikidata.org/wiki/Property:P3563), [3723](https://www.wikidata.org/wiki/Property:P3723), but even [4033](https://www.wikidata.org/wiki/Property:P4033) and more…

Examples:
* Mastodon<br/>`https://tools.wmflabs.org/wikidata-externalid-url/?url=http://%1/@%2&regex=.*@.*&id=$1`
* USCG<br/>`https://tools.wmflabs.org/wikidata-externalid-url/?url=https://msi.nga.mil/queryResults?publications/uscgll?volume=%1&featureNumber=%2&includeRemovals=false&output=html&regex=.*-.*&id=$1`

To avoid issue with `&`,`?`, `=`, … we could use an [urlencoder](https://meyerweb.com/eric/tools/dencoder/) to create manually the URL and `urldecode()` inside your code.
* USCG
  *  url=`https%3A%2F%2Fmsi.nga.mil%2FqueryResults%3Fpublications%2Fuscgll%3Fvolume%3D%251%26featureNumber%3D%252%26includeRemovals%3Dfalse%26output%3Dhtml`
  *  regex=`.*-.*`

**Comment by arthurpsmith** [comment]
@pyrog yes, that would be a very general way to do it; I think the approach I would take on it would be to add a new parameter, 'regex=' as you suggest; handling existing entries as they currently are, but doing something special if the regex parameter is passed. Exactly what regexes to allow may be another question... Also, yes, it is necessary to urlencode = and & characters in the formatter URL (wikidata automatically URL-encodes the ID value it appends, which is another issue). See the formatter URL for P1323 for example.

**Comment by pyrog** [comment]
> Exactly what regexes to allow may be another question...

Yes.

Properties [P1209](https://www.wikidata.org/wiki/Property:P1209), [P6996](https://www.wikidata.org/wiki/Property:P6996), [P1695](https://www.wikidata.org/wiki/Property:P1695)… need 2 regex and 2 urls.

For MMSI [P587](https://www.wikidata.org/wiki/Property:P587), one could link to some national registers, so this property need many url/regex pairs.
* `22[6-8]\d{6}` [French ships](https://maritime-eadministration.anfr.fr/internet-search-navire?typeRecherche=true&mmsi=228081600)
*  `316\d{6}`  [Canadian ships](http://sd.ic.gc.ca/pls/engdoc_anon/mmsi_search.Ship_Search_Single?inMMSI=316337000&invesname=&inname=&oinmmsi=316337000&incallsign=&invesid=&ininmarsat=)

For the [Maritime mobile Access and Retrieval System (MARS)](https://www.itu.int/en/ITU-R/terrestrial/mars/Pages/default.aspx), we need 4 pairs:
* `00\d{7}` [CoastStation](https://www.itu.int/mmsapp/CoastStation/list)
* `111\d{6}` [SearchAndRescueAircraft](https://www.itu.int/mmsapp/SearchAndRescueAircraft/list)
* `99\d{7}` [AidsToNavigation](https://www.itu.int/mmsapp/AidsToNavigation/list)
* `[2-7]\d{8}` [ShipStation](https://www.itu.int/mmsapp/ShipStation/list)


So to be, more universal, the code should accept arrays of URL and regex…

**Comment by pyrog** [comment]
Hi,

I wrote a new version. Could you test and review it please ?
It should be rebased, the examples cleaned and I would like to add a form to url encode parameters...

Regards

**Comment by arthurpsmith** [comment]
@pyrog thanks - looks like it was not a super hard problem after all, I'm glad you tackled this! I've installed the latest version live with your changes, go ahead and try it out with any properties you like...

**Comment by pyrog** [comment]
Thanks 😄 

Tested with:
* NGA Lighthouse ID:
  * [Q42429068](https://www.wikidata.org/wiki/Q42429068#P3563)
  * [Q2085015](https://www.wikidata.org/wiki/Q2085015#P3563)
  * [116-17912.5](https://tools.wmflabs.org/wikidata-externalid-url/?url=https%3A%2F%2Fmsi.nga.mil%2FqueryResults%3Fpublications%2Fngalol%2Flights-buoys%3Fvolume%3D%251%26featureNumber%3D%252%26includeRemovals%3Dfalse%26output%3Dhtml&exp=(%5Cd%7B3%7D)-(.*)&id=116-17912.5)
* USCG Lighthouse ID:
  * [Q7784202](https://www.wikidata.org/wiki/Q7784202#P3723)
  * [Q7073643](https://www.wikidata.org/wiki/Q7073643#P3723)
  * [7-2019.1](https://tools.wmflabs.org/wikidata-externalid-url/?url=https%3A%2F%2Fmsi.nga.mil%2FqueryResults%3Fpublications%2Fuscgll%3Fvolume%3D%251%26featureNumber%3D%252%26includeRemovals%3Dfalse%26output%3Dhtml&exp=(%5Cd)-(.*)&id=7-2019.1)

**Pull request merged**
