### PR TITLE
add support for CN (P1209)

### PR DESCRIPTION
**Pull request by stevenliuyi**
Hi, I added support for the property [P1209](https://www.wikidata.org/wiki/Property:P1209).

### CODE REVIEW

**Comment by arthurpsmith** [comment]
I see what you're trying to do - however, that would break the previous property, also it's not quite following the pattern of the others. I'll take a look.

**Comment by stevenliuyi** [comment]
I'm sorry that I placed it in the wrong place and didn't notice the previous property would break. I've just made a quick fix. Regarding the pattern of the others, do you mean that url_prefix should be used instead of hardcoding the full URL?

**Comment by arthurpsmith** [comment]
Thanks - yes, using the url_prefix is better, so all you would need I think is to set the $link_string to 'typeNum=1&pubCode=$newspaper_id' or the other string depending on the match. Make sense?

**Comment by stevenliuyi** [comment]
Thank you! Let me know if there is still a problem.

**Review by arthurpsmith — APPROVED** [review]

**Comment by arthurpsmith** [comment]
@stevenliuyi Ok, it's merged, and installed, and I added the formatter URL on the property and tested it on a couple of cases, seems to be working - thanks!

**Pull request merged**
